<script>
  import Header from "../lib/components/Header.svelte";
  import Footer from "../lib/components/Footer.svelte";
  import "../app.css";
  import { page } from '$app/stores';
</script>

<svelte:head>
    <title>🔮 RandomObject - Generate Random Objects with AI</title>
    <meta name="description" content="Discover unique and random objects generated by AI. Click to reveal new, fascinating items with detailed descriptions.">
    <meta name="keywords" content="random object, AI generator, unique items, object description, OpenAI">
    <meta property="og:title" content="🔮 RandomObject - AI-Powered Object Generator">
    <meta property="og:description" content="Explore an endless array of AI-generated random objects. Each click reveals a new surprise!">
    <meta property="og:type" content="website">
    <meta property="og:url" content={$page.url.href}>
    <meta name="twitter:card" content="summary_large_image">
    <link rel="canonical" href={$page.url.href}>
</svelte:head>

<div class="flex flex-col min-h-screen">
  <Header />
  <main class="flex-grow">
    <slot />
  </main>
  <Footer/>
</div>
