<script>
    import { enhance } from '$app/forms';
    import { onMount } from 'svelte';
    import RandomObject from '$lib/components/RandomObject.svelte';
    import CategoryList from '$lib/components/CategoryList.svelte';
    import { categories } from '$lib/categories.js';
    import { page } from '$app/stores';

    export let data;

    let { category, randomObjects } = data;
    $: categoryName = categories.find(c => c.id === category)?.name || 'Random';
</script>

<svelte:head>
    <title>🔮 RandomObject Generator</title>
    <meta name="description" content="Discover unique and fascinating objects generated by AI. Click to reveal new items with detailed descriptions.">
</svelte:head>

<div class="max-w-3xl mx-auto space-y-16">
    <section class="">
        <h1 class="text-4xl sm:text-5xl font-bold text-center text-gray-800 mb-2">
            Random Object Generator
        </h1>
        <p class="text-center text-gray-600 mb-8 max-w-xl mx-auto">
            Discover unique and fascinating objects generated by AI. Click to reveal new items with detailed descriptions.
        </p>
        <RandomObject {category} initialObjects={randomObjects} />
    </section>

    <section class="mb-12">
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-4">Categories</h2>
        <CategoryList  />
    </section>

    <section class="mb-12 bg-gray-100 p-8 rounded-lg shadow-md">
        <h2 class="text-3xl font-bold text-center text-gray-800 mb-6">How It Works</h2>
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            {#each [
                { title: "Generate", description: "Our AI-powered system generates a unique random object.", icon: "🤖" },
                { title: "Display", description: "The object is displayed with its name and a detailed description.", icon: "🖼️" },
                { title: "Explore", description: "Click on the object or the 'Generate New Object' button to reveal a new item.", icon: "🔍" }
            ] as step}
                <div class="flex flex-col items-center text-center">
                    <span class="text-4xl mb-2">{step.icon}</span>
                    <h3 class="text-xl font-semibold mb-2">{step.title}</h3>
                    <p class="text-gray-700">{step.description}</p>
                </div>
            {/each}
        </div>
    </section>

    <section class="mb-12 bg-gray-100 p-8 rounded-lg shadow-md">
        <h2 class="text-3xl font-bold text-center text-gray-800 mb-6">Uses for Random Object</h2>
        <ul class="grid grid-cols-1 md:grid-cols-2 gap-4">
            {#each [
                "Creative writing prompts and inspiration",
                "Brainstorming sessions for product design",
                "Ice-breaker activities for team building",
                "Educational tools for expanding vocabulary",
                "Fun party games and conversation starters",
                "Ideas for creative projects"
            ] as use}
                <li class="flex items-center">
                    <svg class="w-6 h-6 text-green-500 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
                    </svg>
                    <span class="text-gray-700">{use}</span>
                </li>
            {/each}
        </ul>
    </section>
</div>

<style>
    .gradient-text {
        background: linear-gradient(45deg, #FF1493, #00BFFF, #FF4500, #1E90FF);
        -webkit-background-clip: text;
        background-clip: text;
        color: transparent;
        animation: gradient 8s ease infinite;
        background-size: 300% 300%;
    }

    @keyframes gradient {
        0% {
            background-position: 0% 50%;
        }
        50% {
            background-position: 100% 50%;
        }
        100% {
            background-position: 0% 50%;
        }
    }
</style>
