<script>
    import { enhance } from '$app/forms';
    import { onMount } from 'svelte';
    import RandomObject from '$lib/components/RandomObject.svelte';
    import CategoryList from '$lib/components/CategoryList.svelte';
    import { categories } from '$lib/categories.js';
    import { page } from '$app/stores';

    export let data;

    let { category, randomObjects } = data;
    $: categoryName = categories.find(c => c.id === category)?.name || 'Random';
</script>

<svelte:head>
    <title>🔮 RandomObject Generator</title>
    <meta name="description" content="Discover unique and fascinating objects generated by AI. Click to reveal new items with detailed descriptions.">
</svelte:head>

<main class="max-w-3xl mx-auto p-6">
    <h1 class="text-4xl font-bold text-center text-gray-800 mb-8">
        Random Object Generator
    </h1>

    <RandomObject {category} initialObjects={randomObjects} />

    <section class="mb-12">
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-4">Categories</h2>
        <CategoryList columns={2} />
    </section>

    <section class="mb-12">
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-4">How It Works</h2>
        <ol class="list-decimal list-inside text-gray-600">
            <li class="mb-2">Our AI-powered system generates a unique random object.</li>
            <li class="mb-2">The object is displayed with its name and a detailed description.</li>
            <li class="mb-2">Click on the object or the "Generate New Object" button to reveal a new item.</li>
        </ol>
    </section>

    <section class="mb-12">
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-4">Uses for RandomObject</h2>
        <ul class="list-disc list-inside text-gray-600">
            <li class="mb-2">Creative writing prompts and inspiration</li>
            <li class="mb-2">Brainstorming sessions for product design</li>
            <li class="mb-2">Ice-breaker activities for team building</li>
            <li class="mb-2">Educational tools for expanding vocabulary and imagination</li>
            <li>Fun party games and conversation starters</li>
        </ul>
    </section>

    <section>
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-4">About RandomObject</h2>
        <p class="text-gray-600 text-center">
            RandomObject is powered by advanced AI technology, leveraging OpenAI's GPT models to create unique and diverse objects. Our goal is to spark creativity, inspire innovation, and provide endless entertainment through the power of artificial intelligence and human imagination.
        </p>
    </section>
</main>

<style>
    .gradient-text {
        background: linear-gradient(45deg, #FF1493, #00BFFF, #FF4500, #1E90FF);
        -webkit-background-clip: text;
        background-clip: text;
        color: transparent;
        animation: gradient 8s ease infinite;
        background-size: 300% 300%;
    }

    @keyframes gradient {
        0% {
            background-position: 0% 50%;
        }
        50% {
            background-position: 100% 50%;
        }
        100% {
            background-position: 0% 50%;
        }
    }
</style>
