<script>
    import { enhance } from '$app/forms';
    import { onMount } from 'svelte';

    export let form;
    export let data;

    let objectQueue = [];
    let currentObject = null;
    let isLoading = false;
    let objectImage = null;
    let photographer = null;
    let imagePageUrl = null;
    let showDescription = false;

    function addObjectsToQueue(objects) {
        objectQueue = [...objectQueue, ...objects];
    }

    function getNextObject() {
        if (objectQueue.length > 0) {
            currentObject = objectQueue.shift();
            if (objectQueue.length === 2) {
                requestNewObjects();
            }
        }
    }

    function requestNewObjects() {
        if (!isLoading) {
            isLoading = true;
            document.getElementById('generateForm').requestSubmit();
        }
    }

    $: if (data.randomObjects && objectQueue.length === 0) {
        addObjectsToQueue(data.randomObjects);
        getNextObject();
    }

    $: if (form?.randomObjects) {
        addObjectsToQueue(form.randomObjects);
    }

    function handleObjectClick(event) {
        // Evitar que se genere un nuevo objeto si se hace clic en el botón de descripción
        if (!event.target.closest('.description-toggle')) {
            getNextObject();
            showDescription = false;
        }
    }

    onMount(() => {
        if (objectQueue.length === 0) {
            requestNewObjects();
        }
    });

    function handleSubmit() {
        return async ({ result }) => {
            if (result.type === 'success') {
                addObjectsToQueue(result.data.randomObjects);
            }
            isLoading = false;
        };
    }

    async function fetchObjectImage(objectName) {
        try {
            const response = await fetch(`/api/image-search?q=${encodeURIComponent(objectName)}`);
            const data = await response.json();
            if (data.imageUrl) {
                objectImage = data.imageUrl;
                photographer = data.photographer;
                imagePageUrl = data.pageUrl;
            } else {
                objectImage = null;
                photographer = null;
                imagePageUrl = null;
            }
        } catch (error) {
            console.error('Error fetching image:', error);
            objectImage = null;
            photographer = null;
            imagePageUrl = null;
        }
    }

    $: if (currentObject) {
        fetchObjectImage(currentObject.name);
    }

    function toggleDescription() {
        showDescription = !showDescription;
    }
</script>

<svelte:head>
    <title>{currentObject ? `${currentObject.name} - RandomObject` : '🔮 RandomObject - AI-Powered Random Object Generator'}</title>
    <meta name="description" content="Discover unique and fascinating random objects generated by AI. Click to reveal new items with detailed descriptions. Perfect for creative inspiration, writing prompts, and more!">
</svelte:head>

<main class="max-w-3xl mx-auto p-6">
    <h1 class="text-4xl font-bold text-center text-gray-800 mb-8">
        <span class="text-5xl" aria-hidden="true">🔮</span> RandomObject
    </h1>
    
    <!-- <section class="mb-12">
        <p class="text-lg text-center text-gray-600 mb-4">
            Welcome to RandomObject, your AI-powered generator for unique and fascinating objects. Click to discover endless possibilities!
        </p>
    </section> -->

    {#if form?.success === false}
    <p class="text-red-500 text-center mb-4" role="alert">Error: {form.error}</p>
    {:else if currentObject}
        <article 
            on:click={handleObjectClick}
            class="bg-gray-100 p-16 rounded-lg mb-8 cursor-pointer hover:bg-gray-200 transition duration-300 relative"
        >
        {#if objectImage}
        <div class="aspect-video overflow-hidden">
            <img src={objectImage} alt={currentObject.name} class="mx-auto aspect-video object-cover max-w-full h-auto rounded-lg shadow-lg" />
        </div>
        <p class="text-sm text-center text-gray-500 mb-4">
            Photo by <a href={imagePageUrl} target="_blank" rel="noopener noreferrer" class="text-blue-500 hover:underline">{photographer}</a> on Pixabay
        </p>
        {:else}
        <p class="text-center text-gray-500 mb-4">No image available</p>
        {/if}
        <h2 class="text-7xl font-extrabold text-center mb-4 gradient-text">{currentObject.name}</h2>
        <p class="text-sm text-center text-gray-600 mt-4">{currentObject.description}</p>
        </article>
    {:else}
        <p class="text-center text-gray-600 mb-8">Generating your first random object...</p>
    {/if}

    <form method="POST" use:enhance={handleSubmit} id="generateForm" class="flex justify-center mb-12">
        <button type="button" on:click={handleObjectClick} class="btn btn-success btn-lg bg-green-500 text-white">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M4 2a1 1 0 011 1v2.101a7.002 7.002 0 0111.601 2.566 1 1 0 11-1.885.666A5.002 5.002 0 005.999 7H9a1 1 0 010 2H4a1 1 0 01-1-1V3a1 1 0 011-1zm.008 9.057a1 1 0 011.276.61A5.002 5.002 0 0014.001 13H11a1 1 0 110-2h5a1 1 0 011 1v5a1 1 0 11-2 0v-2.101a7.002 7.002 0 01-11.601-2.566 1 1 0 01.61-1.276z" clip-rule="evenodd" />
            </svg>
            Generate New Object
        </button>
    </form>

    <section class="mb-12">
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-4">How It Works</h2>
        <ol class="list-decimal list-inside text-gray-600">
            <li class="mb-2">Our AI-powered system generates a unique random object.</li>
            <li class="mb-2">The object is displayed with its name and a detailed description.</li>
            <li class="mb-2">Click on the object or the "Generate New Object" button to reveal a new item.</li>
        </ol>
    </section>

    <section class="mb-12">
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-4">Uses for RandomObject</h2>
        <ul class="list-disc list-inside text-gray-600">
            <li class="mb-2">Creative writing prompts and inspiration</li>
            <li class="mb-2">Brainstorming sessions for product design</li>
            <li class="mb-2">Ice-breaker activities for team building</li>
            <li class="mb-2">Educational tools for expanding vocabulary and imagination</li>
            <li>Fun party games and conversation starters</li>
        </ul>
    </section>

    <section>
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-4">About RandomObject</h2>
        <p class="text-gray-600 text-center">
            RandomObject is powered by advanced AI technology, leveraging OpenAI's GPT models to create unique and diverse objects. Our goal is to spark creativity, inspire innovation, and provide endless entertainment through the power of artificial intelligence and human imagination.
        </p>
    </section>
</main>

<style>
    .gradient-text {
        background: linear-gradient(45deg, #FF1493, #00BFFF, #FF4500, #1E90FF);
        -webkit-background-clip: text;
        background-clip: text;
        color: transparent;
        animation: gradient 8s ease infinite;
        background-size: 300% 300%;
    }

    @keyframes gradient {
        0% {
            background-position: 0% 50%;
        }
        50% {
            background-position: 100% 50%;
        }
        100% {
            background-position: 0% 50%;
        }
    }
</style>
