<script>
    import { enhance } from '$app/forms';
    import RandomObject from '$lib/components/RandomObject.svelte';
    import CategoryList from '$lib/components/CategoryList.svelte';
    import { categories } from '$lib/categories.js';

    export let data;

    let { category, randomObjects, categoryName } = data;
</script>

<svelte:head>
    <title>🔮 {categoryName} Object Generator</title>
    <meta name="description" content="Discover unique and fascinating {categoryName.toLowerCase()} objects generated by AI. Click to reveal new items with detailed descriptions.">
</svelte:head>

<main class="max-w-3xl mx-auto p-6">
    <h1 class="text-3xl sm:text-4xl font-bold text-center text-gray-800 mb-8">
        <span class="text-4xl" aria-hidden="true">{categories.find(c => c.id === category)?.emoji || '🔮'}</span> {categoryName} Object Generator
    </h1>

    <RandomObject {category} initialObjects={randomObjects} />

    <section class="mb-12">
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-4">About {categoryName} Objects</h2>
        <p class="text-gray-600 text-center">
            Explore a wide variety of {categoryName.toLowerCase()} objects generated by our AI. Each object is unique and comes with its own description. Perfect for inspiration, learning, or just for fun!
        </p>
    </section>

    <section class="mb-12">
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-4">Other Categories</h2>
        <CategoryList />
    </section>

    <section>
        <h2 class="text-2xl font-bold text-center text-gray-800 mb-4">How to Use</h2>
        <ol class="list-decimal list-inside text-gray-600">
            <li class="mb-2">Click on the object or the "Generate New Object" button to reveal a new {categoryName.toLowerCase()} item.</li>
            <li class="mb-2">Use the generated objects as prompts for creative writing, brainstorming, or educational purposes.</li>
            <li>Share interesting objects with friends or use them in your projects!</li>
        </ol>
    </section>
</main>
